app:
  datasource:
    post:
      url: jdbc:postgresql://localhost:5432/pdb
      username: pdb
      password: pdb
    comment:
      url: jdbc:postgresql://localhost:5433/cdb
      username: cdb
      password: cdb