app:
  datasource:
    table01:
      url: jdbc:postgresql://localhost:5432/pdb
      username: pdb
      password: pdb
    table02:
      url: jdbc:postgresql://localhost:5433/cdb
      username: cdb
      password: cdb